/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import Model.Customer;
import Model.Product;
import Model.DeliveryPackage;
import javax.swing.JOptionPane;

/**
 *
 * @author thran
 */
public class CreateJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateJPanel
     */
 private DeliveryPackage delPackage;
    private Boolean validate = false;
    
  
    
        public CreateJPanel(){
            initComponents();
        
   
    }
        CreateJPanel(DeliveryPackage deliveryPackage) {
        initComponents();
       
        this.delPackage = deliveryPackage;
    }

  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        packageId = new javax.swing.JTextField();
        packageWt = new javax.swing.JTextField();
        productId1 = new javax.swing.JTextField();
        productName1 = new javax.swing.JTextField();
        productPrice1 = new javax.swing.JTextField();
        custName = new javax.swing.JTextField();
        custId = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnSave = new javax.swing.JButton();
        saveProductBtn = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        add(packageId, new org.netbeans.lib.awtextra.AbsoluteConstraints(92, 10, 60, -1));
        add(packageWt, new org.netbeans.lib.awtextra.AbsoluteConstraints(92, 35, 60, -1));

        productId1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productId1ActionPerformed(evt);
            }
        });
        add(productId1, new org.netbeans.lib.awtextra.AbsoluteConstraints(92, 203, 60, -1));
        add(productName1, new org.netbeans.lib.awtextra.AbsoluteConstraints(92, 232, 60, -1));
        add(productPrice1, new org.netbeans.lib.awtextra.AbsoluteConstraints(92, 270, 60, -1));

        custName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                custNameActionPerformed(evt);
            }
        });
        add(custName, new org.netbeans.lib.awtextra.AbsoluteConstraints(298, 10, 60, -1));
        add(custId, new org.netbeans.lib.awtextra.AbsoluteConstraints(298, 35, 60, -1));

        jLabel1.setText("Package Id");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 13, -1, -1));

        jLabel2.setText("weight");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 38, -1, -1));

        jLabel3.setText("Product Id");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 206, -1, -1));

        jLabel4.setText("ProdName");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 235, -1, -1));

        jLabel5.setText("ProdPrice");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 273, -1, -1));

        jLabel6.setText("Customer name");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(207, 13, -1, -1));

        jLabel7.setText("ID");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 38, -1, -1));

        btnSave.setText("SAVE");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 80, -1, -1));

        saveProductBtn.setText("SAVE PRODUCT");
        saveProductBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveProductBtnActionPerformed(evt);
            }
        });
        add(saveProductBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 269, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        String id= packageId.getText();
        String weight=packageWt.getText();
 
         String customerId= custId.getText();
          String customername=custName.getText();
          
           this.delPackage.setPackageId(Integer.valueOf(id));
        this.delPackage.setPackageWeight(Double.valueOf(weight));
        
     
        Customer customer = this.delPackage.getCustomer();
        customer.setCustomerId(Integer.valueOf(customerId));
        customer.setFullName(customername);
        
        if(validate) {
            JOptionPane.showMessageDialog(null, "Pleae fill all the fields");
        } else {
            JOptionPane.showMessageDialog(null, "Saved!");
        }
                  
        
        
        
    }//GEN-LAST:event_btnSaveActionPerformed

    private void saveProductBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveProductBtnActionPerformed
        // TODO add your handling code here:
        
        String productId = productId1.getText();
        String productName = productName1.getText();
        String productPrice = productPrice1.getText();
        
        Product product = this.delPackage.createProduct(Integer.valueOf(productId), productName, Double.valueOf(productPrice));
       
         JOptionPane.showMessageDialog(null, "Added Product");
    }//GEN-LAST:event_saveProductBtnActionPerformed

    private void productId1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productId1ActionPerformed

    }//GEN-LAST:event_productId1ActionPerformed

    private void custNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_custNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_custNameActionPerformed
private void custName1FocusLost(java.awt.event.FocusEvent evt) {                                    
        // TODO add your handling code here:
        
        System.out.println(custName.getText() + " -> the customer name");
        String name = custName.getText();
        
        if(name.isEmpty()) {
           // JOptionPane.showMessageDialog(null, "Please fill name");
            this.validate = true;
        } else {
            this.validate = false;
        }
    }    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSave;
    private javax.swing.JTextField custId;
    private javax.swing.JTextField custName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField packageId;
    private javax.swing.JTextField packageWt;
    private javax.swing.JTextField productId1;
    private javax.swing.JTextField productName1;
    private javax.swing.JTextField productPrice1;
    private javax.swing.JButton saveProductBtn;
    // End of variables declaration//GEN-END:variables
}
