/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;

import Model.Address;
import Model.Contact;
import Model.Person;
import javax.swing.JOptionPane;

/**
 *
 * @author thran
 */
public class MainJFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainJFrame
     */
    private Person person;
    
    public MainJFrame() {
        initComponents();
        this.person = new Person();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        UserFormPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        saveBtn = new javax.swing.JButton();
        nameFirst = new javax.swing.JTextField();
        fieldStreet = new javax.swing.JTextField();
        numberApt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        nameCity = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        nameState = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        codeZipcode = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        nameLast = new javax.swing.JTextField();
        nameCollege = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        numberId = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        perStreet = new javax.swing.JTextField();
        perApt = new javax.swing.JTextField();
        perCity = new javax.swing.JTextField();
        perState = new javax.swing.JTextField();
        perZipcode = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        phoneOfc = new javax.swing.JTextField();
        phonePer = new javax.swing.JTextField();
        emailOfc = new javax.swing.JTextField();
        emailPer = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        ViewJPanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        viewFirstName = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        viewStreet = new javax.swing.JLabel();
        viewApt = new javax.swing.JLabel();
        viewCity = new javax.swing.JLabel();
        viewState = new javax.swing.JLabel();
        viewZipcode = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        viewLastName = new javax.swing.JLabel();
        viewCollegeName = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        viewNuid = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        viewpStreet = new javax.swing.JLabel();
        viewpApt = new javax.swing.JLabel();
        viewpCity = new javax.swing.JLabel();
        viewpState = new javax.swing.JLabel();
        viewpZipcode = new javax.swing.JLabel();
        viewphoneOfc = new javax.swing.JLabel();
        viewphonePer = new javax.swing.JLabel();
        viewemailOfc = new javax.swing.JLabel();
        viewemailPer = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        UserFormPanel.setBackground(new java.awt.Color(51, 255, 255));
        UserFormPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("FIRST NAME");
        UserFormPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        jLabel2.setText("STREET");
        UserFormPanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, -1, -1));

        saveBtn.setText("SAVE");
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });
        UserFormPanel.add(saveBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 360, -1, -1));

        nameFirst.setText("thranathi");
        nameFirst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameFirstActionPerformed(evt);
            }
        });
        UserFormPanel.add(nameFirst, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, 90, -1));

        fieldStreet.setText("boston");
        fieldStreet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldStreetActionPerformed(evt);
            }
        });
        UserFormPanel.add(fieldStreet, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, 90, -1));

        numberApt.setText("108");
        UserFormPanel.add(numberApt, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, 70, -1));

        jLabel4.setText("APT");
        UserFormPanel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, -1, -1));

        nameCity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameCityActionPerformed(evt);
            }
        });
        UserFormPanel.add(nameCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, 70, -1));

        jLabel6.setText("CITY");
        UserFormPanel.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, -1, -1));

        nameState.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameStateActionPerformed(evt);
            }
        });
        UserFormPanel.add(nameState, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, 70, -1));

        jLabel7.setText("STATE");
        UserFormPanel.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, -1, -1));
        UserFormPanel.add(codeZipcode, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, 70, -1));

        jLabel8.setText("ZIPCODE");
        UserFormPanel.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, -1, -1));

        jLabel13.setText("LAST NAME");
        UserFormPanel.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));
        UserFormPanel.add(nameLast, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, 70, -1));
        UserFormPanel.add(nameCollege, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, 60, -1));

        jLabel15.setText("College Name");
        UserFormPanel.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));
        UserFormPanel.add(numberId, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 0, 80, -1));

        jLabel17.setText("Nuid");
        UserFormPanel.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, -1, -1));
        UserFormPanel.add(perStreet, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, 70, -1));
        UserFormPanel.add(perApt, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, 70, -1));

        perCity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                perCityActionPerformed(evt);
            }
        });
        UserFormPanel.add(perCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 220, 70, -1));
        UserFormPanel.add(perState, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 240, 70, -1));
        UserFormPanel.add(perZipcode, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 260, 70, -1));

        jLabel19.setText("perm street");
        UserFormPanel.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, -1, -1));

        jLabel20.setText("perm apt");
        UserFormPanel.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, -1, -1));

        jLabel21.setText("perm city");
        UserFormPanel.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, -1, -1));

        jLabel22.setText("perm state");
        UserFormPanel.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, -1, -1));

        jLabel23.setText("perm zipcode");
        UserFormPanel.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, -1, -1));

        phoneOfc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phoneOfcActionPerformed(evt);
            }
        });
        UserFormPanel.add(phoneOfc, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 280, 70, -1));

        phonePer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phonePerActionPerformed(evt);
            }
        });
        UserFormPanel.add(phonePer, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 300, 70, -1));
        UserFormPanel.add(emailOfc, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 320, 70, -1));
        UserFormPanel.add(emailPer, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 340, 70, -1));

        jLabel29.setText("ofc phone");
        UserFormPanel.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 280, -1, -1));

        jLabel30.setText("per phone");
        UserFormPanel.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 300, -1, -1));

        jLabel31.setText("ofc mail");
        UserFormPanel.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 320, -1, -1));

        jLabel32.setText("personal mail");
        UserFormPanel.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 340, -1, -1));

        jSplitPane1.setLeftComponent(UserFormPanel);

        jLabel3.setText("first name");

        viewFirstName.setText("jLabel4");

        jLabel5.setText("Street");

        viewStreet.setText("jLabel6");

        viewApt.setText("jLabel9");

        viewCity.setText("jLabel9");

        viewState.setText("jLabel9");

        viewZipcode.setText("jLabel9");

        jLabel9.setText("Apt");

        jLabel10.setText("City");

        jLabel11.setText("State");

        jLabel12.setText("Zipcode");

        jLabel14.setText("Last name");

        viewLastName.setText("jLabel15");

        viewCollegeName.setText("jLabel16");

        jLabel16.setText("College Name");

        viewNuid.setText("jLabel18");

        jLabel18.setText("nuid");

        jLabel24.setText("perm street");

        jLabel25.setText("perm apt");

        jLabel26.setText("perm city");

        jLabel27.setText("perm state");

        jLabel28.setText("perm zipcode");

        viewpStreet.setText("jLabel29");

        viewpApt.setText("jLabel30");

        viewpCity.setText("jLabel31");

        viewpState.setText("jLabel32");

        viewpZipcode.setText("jLabel33");

        viewphoneOfc.setText("jLabel33");

        viewphonePer.setText("jLabel34");

        viewemailOfc.setText("jLabel35");

        viewemailPer.setText("jLabel36");

        jLabel37.setText("ofc phone");

        jLabel38.setText("per phone");

        jLabel39.setText("ofc mail");

        jLabel40.setText("per mail");

        javax.swing.GroupLayout ViewJPanelLayout = new javax.swing.GroupLayout(ViewJPanel);
        ViewJPanel.setLayout(ViewJPanelLayout);
        ViewJPanelLayout.setHorizontalGroup(
            ViewJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ViewJPanelLayout.createSequentialGroup()
                .addGroup(ViewJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ViewJPanelLayout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addGroup(ViewJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ViewJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel26, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel27, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel28, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel37, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel38, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel39, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel40, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(ViewJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(viewemailPer, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(viewemailOfc, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(viewphonePer, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(viewphoneOfc, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(viewpZipcode, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(viewNuid, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(viewCity, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(viewCollegeName, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(viewLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(viewZipcode, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(viewState, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(viewApt, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(viewFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(viewStreet, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(viewpStreet, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(viewpApt, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(viewpCity, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(viewpState, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(148, Short.MAX_VALUE))
        );
        ViewJPanelLayout.setVerticalGroup(
            ViewJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ViewJPanelLayout.createSequentialGroup()
                .addGroup(ViewJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(viewNuid)
                    .addComponent(jLabel18))
                .addGap(7, 7, 7)
                .addGroup(ViewJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(viewFirstName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ViewJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(viewLastName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ViewJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(viewCollegeName)
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ViewJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(viewStreet))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ViewJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(viewApt))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ViewJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(viewCity))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ViewJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(viewState))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ViewJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(viewZipcode))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ViewJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(viewpStreet)
                    .addComponent(jLabel24))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ViewJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(viewpApt)
                    .addComponent(jLabel25))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ViewJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(viewpCity)
                    .addComponent(jLabel26))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ViewJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(viewpState)
                    .addComponent(jLabel27))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ViewJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(viewpZipcode)
                    .addComponent(jLabel28))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ViewJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(viewphoneOfc)
                    .addComponent(jLabel37))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ViewJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(viewphonePer)
                    .addComponent(jLabel38))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ViewJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(viewemailOfc)
                    .addComponent(jLabel39))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ViewJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(viewemailPer)
                    .addComponent(jLabel40))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        jSplitPane1.setRightComponent(ViewJPanel);

        getContentPane().add(jSplitPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nameFirstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameFirstActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameFirstActionPerformed

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
        // TODO add your handling code here:
        //logic to save the person details
        int nuid= Integer.valueOf(numberId.getText());
        String firstName= nameFirst.getText();
        String lastName= nameLast.getText();
        String collegeName= nameCollege.getText();
        String street= fieldStreet.getText();
        int apt= Integer.valueOf(numberApt.getText());
        String city= nameCity.getText();
        String state= nameState.getText();
        int zipcode= Integer.valueOf(codeZipcode.getText());
        String pstreet= perStreet.getText();
        int papt= Integer.valueOf(perApt.getText());
        String pcity= perCity.getText();
        String pstate= perState.getText();
        int pzipcode= Integer.valueOf(perZipcode.getText());
        
        long perphoneNumber = Long.valueOf(phonePer.getText());
        long ofcphoneNumber = Long.valueOf(phoneOfc.getText());
        String peremailId = emailPer.getText();
        String ofcemailId = emailOfc.getText();
        
        
        
        
        
        
        this.person.setNuid(nuid);
        this.person.setfirstName(firstName);
        this.person.setlastName(lastName);
        this.person.setcollegeName(collegeName);
        Address address = this.person.getAddress();
        address.setStreet(street);
        address.setApt(apt);
        address.setCity(city);
        
        address.setState(state);
        address.setZipcode(zipcode);
        address.setpStreet(pstreet);
        address.setpApt(papt);
        address.setpCity(pcity);
        address.setpState(pstate);
        address.setpZipcode(pzipcode);
        
        Contact contact = this.person.getContact();
        contact.setofcPhoneNumber(ofcphoneNumber);
        contact.setofcEmailID(ofcemailId);
        contact.setperPhoneNumber(perphoneNumber);
        contact.setperEmailID(peremailId);
        
        
        
        
        //this.contact.setofcphoneNumber(ofcphoneNumber);
        //this.contact.setperphoneNumber(perphoneNumber);
        //this.contact.setofcemailID(ofcemailID);
        //this.contact.setperemailID(peremailID);
        
        
        
        
        JOptionPane.showMessageDialog(null, "SAVED SUCCESSFULLY");
        
        display();
    }//GEN-LAST:event_saveBtnActionPerformed

    private void fieldStreetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldStreetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldStreetActionPerformed

    private void nameCityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameCityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameCityActionPerformed

    private void nameStateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameStateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameStateActionPerformed

    private void perCityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_perCityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_perCityActionPerformed

    private void phoneOfcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phoneOfcActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phoneOfcActionPerformed

    private void phonePerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phonePerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phonePerActionPerformed

    private void display(){
        
    //Person obj2= new Person();
    viewNuid.setText(String.valueOf(this.person.getNuid()));  
    viewFirstName.setText(this.person.getfirstName());
    viewLastName.setText(this.person.getlastName()); 
    viewCollegeName.setText(this.person.getcollegeName());
    viewStreet.setText(this.person.getAddress().getStreet());
    viewApt.setText(String.valueOf(this.person.getAddress().getApt()));
    viewCity.setText(this.person.getAddress().getCity());
    viewState.setText(this.person.getAddress().getState());
    viewZipcode.setText(String.valueOf(this.person.getAddress().getZipcode()));
    viewpStreet.setText(this.person.getAddress().getpStreet());
    viewpApt.setText(String.valueOf(this.person.getAddress().getpApt()));
    viewpCity.setText(this.person.getAddress().getpCity());
    viewpState.setText(this.person.getAddress().getpState());
    viewpZipcode.setText(String.valueOf(this.person.getAddress().getpZipcode()));
    
    
    viewphonePer.setText(String.valueOf(this.person.getContact(). getperPhoneNumber()));
    viewphoneOfc.setText(String.valueOf(this.person.getContact().getofcPhoneNumber()));
    viewemailOfc.setText(this.person.getContact().getofcEmailID());
    viewemailPer.setText(this.person.getContact().getperEmailID());
    
    
    
    
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel UserFormPanel;
    private javax.swing.JPanel ViewJPanel;
    private javax.swing.JTextField codeZipcode;
    private javax.swing.JTextField emailOfc;
    private javax.swing.JTextField emailPer;
    private javax.swing.JTextField fieldStreet;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTextField nameCity;
    private javax.swing.JTextField nameCollege;
    private javax.swing.JTextField nameFirst;
    private javax.swing.JTextField nameLast;
    private javax.swing.JTextField nameState;
    private javax.swing.JTextField numberApt;
    private javax.swing.JTextField numberId;
    private javax.swing.JTextField perApt;
    private javax.swing.JTextField perCity;
    private javax.swing.JTextField perState;
    private javax.swing.JTextField perStreet;
    private javax.swing.JTextField perZipcode;
    private javax.swing.JTextField phoneOfc;
    private javax.swing.JTextField phonePer;
    private javax.swing.JButton saveBtn;
    private javax.swing.JLabel viewApt;
    private javax.swing.JLabel viewCity;
    private javax.swing.JLabel viewCollegeName;
    private javax.swing.JLabel viewFirstName;
    private javax.swing.JLabel viewLastName;
    private javax.swing.JLabel viewNuid;
    private javax.swing.JLabel viewState;
    private javax.swing.JLabel viewStreet;
    private javax.swing.JLabel viewZipcode;
    private javax.swing.JLabel viewemailOfc;
    private javax.swing.JLabel viewemailPer;
    private javax.swing.JLabel viewpApt;
    private javax.swing.JLabel viewpCity;
    private javax.swing.JLabel viewpState;
    private javax.swing.JLabel viewpStreet;
    private javax.swing.JLabel viewpZipcode;
    private javax.swing.JLabel viewphoneOfc;
    private javax.swing.JLabel viewphonePer;
    // End of variables declaration//GEN-END:variables
}
